//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDFMergeSplitSample.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDFMergeSplitSample.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DLL not found..
        /// </summary>
        internal static string MsgDLLNotFound {
            get {
                return ResourceManager.GetString("MsgDLLNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found:.
        /// </summary>
        internal static string MsgFileNotFound {
            get {
                return ResourceManager.GetString("MsgFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF file couldn&apos;t be opened: .
        /// </summary>
        internal static string MsgFileNotOpen {
            get {
                return ResourceManager.GetString("MsgFileNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select input and output PDF files..
        /// </summary>
        internal static string MsgNoFileSelected {
            get {
                return ResourceManager.GetString("MsgNoFileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output PDF file couldn&apos;t be created:.
        /// </summary>
        internal static string MsgOutputNotCreated {
            get {
                return ResourceManager.GetString("MsgOutputNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon pdf_tools {
            get {
                object obj = ResourceManager.GetObject("pdf_tools", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merged documents.
        /// </summary>
        internal static string StrTitleMerge {
            get {
                return ResourceManager.GetString("StrTitleMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split 1.
        /// </summary>
        internal static string StrTitleSplit1 {
            get {
                return ResourceManager.GetString("StrTitleSplit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split 2.
        /// </summary>
        internal static string StrTitleSplit2 {
            get {
                return ResourceManager.GetString("StrTitleSplit2", resourceCulture);
            }
        }
    }
}
